import 'package:the_accountant/data/datasources/local/app_database.dart'
    show Transaction;
import 'package:the_accountant/data/models/transaction.dart'
    show TransactionSpecialType, TransactionType;

/// The single, authoritative eligibility policy for every financial calculation
/// in the app.
///
/// Balance math, reports, budgets, category analytics, forecasts, and
/// credit/debt settlement all used to carry their own slightly different
/// filters, which is why the dashboard, the reports tab, and the stored wallet
/// balance could disagree about the same set of rows. Everything now routes
/// through these predicates instead, so there is exactly one definition of each
/// concept and changing it changes every consumer at once.
///
/// ## The four independent concepts
///
/// 1. **Cash realization** ([affectsWalletBalance]) — has the money actually
///    moved in or out of the wallet? A lend/borrow moves cash immediately, so it
///    is realized the moment it is recorded. An unpaid *upcoming* item has not
///    moved yet, so it is not.
/// 2. **Debt settlement** ([isSettled]) — has a receivable/payable been repaid
///    in full? This is derived from [Transaction.paidAmount] versus
///    [Transaction.amount] and is completely independent of concept 1. A brand
///    new loan is realized (cash moved) but *not* settled (nothing repaid).
///    Conflating these two was the "new loan shows as Settled" defect.
/// 3. **Analytics eligibility** ([countsAsIncome] / [countsAsExpense] /
///    [countsTowardCategorySpending]) — should the row appear in gross
///    earnings/spending? Realized *and* not an internal wallet-to-wallet
///    transfer.
/// 4. **Forecast eligibility** ([isForecast]) — is this a not-yet-happened item
///    that belongs in upcoming/projection views only, never in realized totals?
class TransactionPolicy {
  const TransactionPolicy._();

  // ---------------------------------------------------------------------------
  // Classification
  // ---------------------------------------------------------------------------

  /// Value stored in [Transaction.transactionType] for the two legs of a
  /// wallet-to-wallet transfer.
  static String get regularType => TransactionType.regular.storageValue;

  static String get transferType => TransactionType.transfer.storageValue;

  /// Value stored in [Transaction.transactionType] for generated recurrence
  /// occurrences.
  static String get recurringInstanceType =>
      TransactionType.recurringInstance.storageValue;

  /// How this row came to exist. Parsing goes through [TransactionType] so the
  /// column, the wire format, and this policy can never disagree about what a
  /// generated occurrence or a transfer leg looks like.
  static TransactionType kindOf(Transaction t) =>
      TransactionType.fromStorage(t.transactionType);

  /// Whether the row was generated by a recurrence schedule.
  static bool isRecurringInstance(Transaction t) =>
      kindOf(t) == TransactionType.recurringInstance;

  /// Whether the row is one leg of a wallet-to-wallet transfer.
  ///
  /// Transfers move money *between the user's own wallets*. Each leg legitimately
  /// changes its wallet's balance, but the pair is net-zero for the user, so a
  /// transfer must never be counted as income, expense, category spending,
  /// budget spending, or report earnings — otherwise every internal movement
  /// inflates gross income and gross expense by the same amount.
  static bool isTransfer(Transaction t) =>
      kindOf(t) == TransactionType.transfer;

  /// Whether the row is a lend (`credit`) or borrow (`debt`) entry.
  static bool isCreditOrDebt(Transaction t) =>
      t.specialType == TransactionSpecialType.credit ||
      t.specialType == TransactionSpecialType.debt;

  /// Whether the row is a lend entry (someone owes the user money).
  static bool isCredit(Transaction t) =>
      t.specialType == TransactionSpecialType.credit;

  /// Whether the row is a borrow entry (the user owes someone money).
  static bool isDebt(Transaction t) =>
      t.specialType == TransactionSpecialType.debt;

  /// Whether the row is a not-yet-paid scheduled item.
  static bool isUpcoming(Transaction t) =>
      t.specialType == TransactionSpecialType.upcoming;

  /// Whether the row still exists (not soft-deleted).
  static bool isLive(Transaction t) => t.deletedAt == null;

  // ---------------------------------------------------------------------------
  // 1. Cash realization — the wallet-balance effect
  // ---------------------------------------------------------------------------

  /// Whether this transaction's cash has actually moved, and therefore whether
  /// it contributes to the wallet's running balance.
  ///
  /// This is the canonical balance predicate. [WalletBalanceService], the
  /// schema-11 migration backfill, transaction creation, transaction deletion,
  /// and every reporting figure derive from it, so a create and its matching
  /// delete can never disagree about whether a row counted.
  ///
  /// Credit/debt entries count regardless of [Transaction.isPaid] because the
  /// principal genuinely left (lend) or entered (borrow) the wallet when the
  /// loan was recorded; their repayment is tracked separately by
  /// [Transaction.paidAmount] and by the separate repayment transactions.
  static bool affectsWalletBalance(Transaction t) {
    if (!isLive(t)) return false;
    return t.isPaid || isCreditOrDebt(t);
  }

  /// Signed effect of [t] on its wallet's balance, in integer minor units.
  ///
  /// Returns 0 when the transaction is not realized. Amounts are stored as
  /// magnitudes, so direction comes from [Transaction.isIncome] alone.
  static int walletBalanceEffect(Transaction t) {
    if (!affectsWalletBalance(t)) return 0;
    return t.isIncome ? t.amount.abs() : -t.amount.abs();
  }

  // ---------------------------------------------------------------------------
  // 2. Debt settlement — completely separate from cash realization
  // ---------------------------------------------------------------------------

  /// Whether a receivable/payable has been repaid in full.
  ///
  /// This is the ONLY settlement rule in the app. It is deliberately derived
  /// from amounts rather than from [Transaction.isPaid]: `isPaid` means "the
  /// cash movement happened", which is true for a brand new loan that has not
  /// been repaid at all. Labels, filters, unpaid tabs, the record-payment and
  /// settle actions, and overdue reminders all call this.
  ///
  /// A non-positive [Transaction.amount] is treated as settled so a zero-value
  /// row can never sit in the outstanding list forever.
  static bool isSettled(Transaction t) {
    if (t.amount <= 0) return true;
    return t.paidAmount >= t.amount;
  }

  /// The remaining unpaid principal of a receivable/payable, in minor units.
  ///
  /// Clamped at zero so an overpayment (paidAmount > amount) reads as fully
  /// settled rather than as a negative outstanding balance that would silently
  /// offset other loans in the exposure total.
  static int outstandingAmount(Transaction t) {
    final remaining = t.amount - t.paidAmount;
    return remaining > 0 ? remaining : 0;
  }

  /// Whether a credit/debt row is still owed (partially or entirely).
  static bool isOutstanding(Transaction t) => !isSettled(t);

  /// Whether a credit/debt row is past its due date and still owed.
  ///
  /// [now] is injectable so tests are not clock-dependent.
  static bool isOverdue(Transaction t, {DateTime? now}) {
    if (isSettled(t)) return false;
    final due = t.originalDueDate ?? t.date;
    return due.isBefore(now ?? DateTime.now());
  }

  /// Whether a partial (but not complete) repayment has been recorded.
  static bool hasPartialPayment(Transaction t) =>
      t.paidAmount > 0 && !isSettled(t);

  /// Repayment progress in the range 0.0–1.0, for progress bars.
  static double settlementProgress(Transaction t) {
    if (t.amount <= 0) return 1.0;
    final ratio = t.paidAmount / t.amount;
    return ratio.clamp(0.0, 1.0);
  }

  // ---------------------------------------------------------------------------
  // 3. Analytics eligibility — reports, dashboards, categories, budgets
  // ---------------------------------------------------------------------------

  /// Whether the row belongs in *any* earnings/spending analytic.
  ///
  /// Realized cash movement that is not an internal transfer.
  static bool countsInAnalytics(Transaction t) =>
      affectsWalletBalance(t) && !isTransfer(t);

  /// Whether the row counts toward gross income / report earnings.
  static bool countsAsIncome(Transaction t) =>
      countsInAnalytics(t) && t.isIncome;

  /// Whether the row counts toward gross expense / report spending.
  static bool countsAsExpense(Transaction t) =>
      countsInAnalytics(t) && !t.isIncome;

  /// Whether the row counts toward per-category spending totals.
  ///
  /// Identical to [countsAsExpense] by design — category analytics and expense
  /// totals must never diverge. It exists as its own name so call sites read
  /// clearly and so a future divergence has to be made deliberately here.
  static bool countsTowardCategorySpending(Transaction t) => countsAsExpense(t);

  /// Whether the row counts toward a budget's consumed amount.
  ///
  /// A budget tracks either spending (`isIncome == false`) or earnings
  /// (`isIncome == true`); [budgetIsIncome] selects which side, and
  /// [budgetCategoryId] optionally narrows it to one category.
  static bool countsTowardBudget(
    Transaction t, {
    bool budgetIsIncome = false,
    String? budgetCategoryId,
  }) {
    if (!countsInAnalytics(t)) return false;
    if (t.isIncome != budgetIsIncome) return false;
    if (budgetCategoryId != null &&
        budgetCategoryId.isNotEmpty &&
        t.categoryId != budgetCategoryId) {
      return false;
    }
    return true;
  }

  // ---------------------------------------------------------------------------
  // 4. Forecast eligibility
  // ---------------------------------------------------------------------------

  /// Whether the row is a pending scheduled item that belongs in forecast and
  /// upcoming views ONLY — never in realized reports or wallet balances.
  ///
  /// Skipped occurrences are excluded: the user has explicitly said this one
  /// will not happen.
  static bool isForecast(Transaction t) =>
      isLive(t) && !t.isPaid && !t.skipPaid && isUpcoming(t);

  /// Whether a forecast item is due in the future.
  static bool isFutureForecast(Transaction t, {DateTime? now}) =>
      isForecast(t) && t.date.isAfter(now ?? DateTime.now());

  /// Whether a forecast item is already past due.
  static bool isOverdueForecast(Transaction t, {DateTime? now}) =>
      isForecast(t) && !t.date.isAfter(now ?? DateTime.now());

  // ---------------------------------------------------------------------------
  // Aggregate helpers
  // ---------------------------------------------------------------------------

  /// Sum of realized income over [transactions], in minor units.
  static int totalIncome(Iterable<Transaction> transactions) => transactions
      .where(countsAsIncome)
      .fold<int>(0, (sum, t) => sum + t.amount.abs());

  /// Sum of realized expense over [transactions], in minor units.
  static int totalExpense(Iterable<Transaction> transactions) => transactions
      .where(countsAsExpense)
      .fold<int>(0, (sum, t) => sum + t.amount.abs());

  /// Total still owed across [transactions], in minor units.
  static int totalOutstanding(Iterable<Transaction> transactions) =>
      transactions
          .where(isLive)
          .fold<int>(0, (sum, t) => sum + outstandingAmount(t));

  /// Spending grouped by category id, in minor units. Rows without a category
  /// are grouped under [uncategorizedKey].
  static Map<String, int> spendingByCategory(
    Iterable<Transaction> transactions,
  ) {
    final result = <String, int>{};
    for (final t in transactions.where(countsTowardCategorySpending)) {
      final key = t.categoryId ?? uncategorizedKey;
      result[key] = (result[key] ?? 0) + t.amount.abs();
    }
    return result;
  }

  /// Grouping key used for transactions with no category assigned.
  static const String uncategorizedKey = 'uncategorized';
}
