name: the_accountant
description: "A personal finance management application with a focus on privacy, local-first storage, and beautiful UI/UX."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State management
  flutter_riverpod: ^3.0.0
  riverpod_annotation: ^3.0.0
  
  # Database
  drift: ^2.20.0
  sqlite3_flutter_libs: ^0.5.24
  
  # Firebase
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  firebase_analytics: ^12.0.0
  firebase_messaging: ^16.0.0
  
  # UI/Animations
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  animated_text_kit: ^4.2.2
  fl_chart: ^1.0.0
  
  # Networking and APIs
  http: ^1.2.2
  google_sign_in: ^7.1.1
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  extension_google_sign_in_as_googleapis_auth: ^3.0.0
  
  # Environment
  flutter_dotenv: ^6.0.0
  
  # Security
  flutter_secure_storage: ^9.2.4
  
  # Utilities
  intl: ^0.20.2
  uuid: ^4.5.1
  equatable: ^2.0.5
  crypto: ^3.0.5
  path: ^1.9.0
  path_provider: ^2.1.4
  share_plus: ^12.0.0
  url_launcher: ^6.3.0
  permission_handler: ^12.0.1
  flutter_local_notifications: ^19.4.1
  pdf: ^3.10.8
  printing: ^5.12.6
  image_picker: ^1.0.4
  in_app_purchase: ^3.1.11
  
  # OCR
  google_mlkit_text_recognition: ^0.15.0
  google_mlkit_barcode_scanning: ^0.14.1
  google_mlkit_image_labeling: ^0.14.1
  # google_mlkit_face_detection: 0.12.0  # Commenting out as not needed for receipts

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # Code generation
  riverpod_generator: ^3.0.0
  build_runner: ^2.4.11
  drift_dev: ^2.20.0

flutter:
  uses-material-design: true

  assets:
    - .env
  #   - assets/
  #   - assets/animations/
  #   - assets/icons/
  #   - assets/images/
