import 'package:flutter/material.dart';

/// Icon registry for mapping icon names to IconData.
/// This allows storing icon references as strings in the database
/// while rendering actual Material icons in the UI.
class IconRegistry {
  /// Private constructor to prevent instantiation
  IconRegistry._();

  /// Comprehensive map of icon names to IconData.
  /// Organized by category for easy maintenance.
  static final Map<String, IconData> _icons = {
    // === FOOD & DRINKS ===
    'restaurant': Icons.restaurant,
    'food': Icons.restaurant,
    'fastfood': Icons.fastfood,
    'local_cafe': Icons.local_cafe,
    'coffee': Icons.coffee,
    'local_bar': Icons.local_bar,
    'liquor': Icons.liquor,
    'local_pizza': Icons.local_pizza,
    'lunch_dining': Icons.lunch_dining,
    'dinner_dining': Icons.dinner_dining,
    'breakfast_dining': Icons.breakfast_dining,
    'bakery_dining': Icons.bakery_dining,
    'icecream': Icons.icecream,
    'cake': Icons.cake,
    'cookie': Icons.cookie,
    'set_meal': Icons.set_meal,
    'ramen_dining': Icons.ramen_dining,
    'takeout_dining': Icons.takeout_dining,
    'emoji_food_beverage': Icons.emoji_food_beverage,

    // === TRANSPORTATION ===
    'directions_car': Icons.directions_car,
    'car': Icons.directions_car,
    'transport': Icons.directions_car,
    'local_gas_station': Icons.local_gas_station,
    'gas': Icons.local_gas_station,
    'fuel': Icons.local_gas_station,
    'directions_bus': Icons.directions_bus,
    'bus': Icons.directions_bus,
    'train': Icons.train,
    'subway': Icons.subway,
    'tram': Icons.tram,
    'flight': Icons.flight,
    'airplane': Icons.flight,
    'directions_boat': Icons.directions_boat,
    'boat': Icons.directions_boat,
    'two_wheeler': Icons.two_wheeler,
    'motorcycle': Icons.two_wheeler,
    'pedal_bike': Icons.pedal_bike,
    'bike': Icons.pedal_bike,
    'electric_scooter': Icons.electric_scooter,
    'local_taxi': Icons.local_taxi,
    'taxi': Icons.local_taxi,
    'local_parking': Icons.local_parking,
    'parking': Icons.local_parking,
    'ev_station': Icons.ev_station,
    'car_repair': Icons.car_repair,
    'car_rental': Icons.car_rental,
    'commute': Icons.commute,

    // === SHOPPING ===
    'shopping_bag': Icons.shopping_bag,
    'shopping': Icons.shopping_bag,
    'shopping_cart': Icons.shopping_cart,
    'cart': Icons.shopping_cart,
    'local_mall': Icons.local_mall,
    'mall': Icons.local_mall,
    'store': Icons.store,
    'storefront': Icons.storefront,
    'checkroom': Icons.checkroom,
    'clothes': Icons.checkroom,
    'dry_cleaning': Icons.dry_cleaning,
    'watch': Icons.watch,
    'diamond': Icons.diamond,
    'redeem': Icons.redeem,
    'gift': Icons.redeem,
    'card_giftcard': Icons.card_giftcard,
    'local_offer': Icons.local_offer,
    'sell': Icons.sell,
    'loyalty': Icons.loyalty,

    // === HOME & UTILITIES ===
    'home': Icons.home,
    'house': Icons.house,
    'apartment': Icons.apartment,
    'cottage': Icons.cottage,
    'villa': Icons.villa,
    'bed': Icons.bed,
    'bedroom': Icons.king_bed,
    'king_bed': Icons.king_bed,
    'chair': Icons.chair,
    'table_restaurant': Icons.table_restaurant,
    'kitchen': Icons.kitchen,
    'bathroom': Icons.bathroom,
    'bathtub': Icons.bathtub,
    'shower': Icons.shower,
    'lightbulb': Icons.lightbulb,
    'electricity': Icons.lightbulb,
    'power': Icons.power,
    'bolt': Icons.bolt,
    'water_drop': Icons.water_drop,
    'water': Icons.water_drop,
    'local_fire_department': Icons.local_fire_department,
    'propane_tank': Icons.propane_tank,
    'gas_meter': Icons.gas_meter,
    'heat_pump': Icons.heat_pump,
    'air': Icons.air,
    'ac_unit': Icons.ac_unit,
    'thermostat': Icons.thermostat,
    'cleaning_services': Icons.cleaning_services,
    'cleaning': Icons.cleaning_services,
    'hardware': Icons.hardware,
    'plumbing': Icons.plumbing,
    'handyman': Icons.handyman,
    'construction': Icons.construction,
    'home_repair_service': Icons.home_repair_service,
    'roofing': Icons.roofing,
    'fence': Icons.fence,
    'yard': Icons.yard,
    'grass': Icons.grass,

    // === BILLS & PAYMENTS ===
    'receipt': Icons.receipt,
    'bills': Icons.receipt,
    'receipt_long': Icons.receipt_long,
    'payments': Icons.payments,
    'payment': Icons.payment,
    'credit_card': Icons.credit_card,
    'account_balance': Icons.account_balance,
    'bank': Icons.account_balance,
    'account_balance_wallet': Icons.account_balance_wallet,
    'wallet': Icons.account_balance_wallet,
    'attach_money': Icons.attach_money,
    'money': Icons.attach_money,
    'currency_exchange': Icons.currency_exchange,
    'price_change': Icons.price_change,
    'savings': Icons.savings,
    'piggy_bank': Icons.savings,
    'paid': Icons.paid,
    'request_quote': Icons.request_quote,
    'point_of_sale': Icons.point_of_sale,
    'local_atm': Icons.local_atm,
    'atm': Icons.local_atm,

    // === COMMUNICATION & TECH ===
    'phone': Icons.phone,
    'phone_android': Icons.phone_android,
    'phone_iphone': Icons.phone_iphone,
    'smartphone': Icons.smartphone,
    'mobile': Icons.smartphone,
    'tablet': Icons.tablet,
    'tablet_android': Icons.tablet_android,
    'laptop': Icons.laptop,
    'computer': Icons.computer,
    'desktop_windows': Icons.desktop_windows,
    'devices': Icons.devices,
    'wifi': Icons.wifi,
    'internet': Icons.wifi,
    'router': Icons.router,
    'cell_tower': Icons.cell_tower,
    'signal_cellular_alt': Icons.signal_cellular_alt,
    'cable': Icons.cable,
    'tv': Icons.tv,
    'television': Icons.tv,
    'monitor': Icons.monitor,
    'videogame_asset': Icons.videogame_asset,
    'games': Icons.videogame_asset,
    'sports_esports': Icons.sports_esports,
    'esports': Icons.sports_esports,
    'headset': Icons.headset,
    'headphones': Icons.headphones,
    'speaker': Icons.speaker,
    'music_note': Icons.music_note,
    'music': Icons.music_note,
    'audiotrack': Icons.audiotrack,
    'camera': Icons.camera,
    'camera_alt': Icons.camera_alt,
    'photo_camera': Icons.photo_camera,
    'videocam': Icons.videocam,
    'movie': Icons.movie,
    'theaters': Icons.theaters,

    // === ENTERTAINMENT ===
    'movie_filter': Icons.movie_filter,
    'entertainment': Icons.movie,
    'local_movies': Icons.local_movies,
    'live_tv': Icons.live_tv,
    'smart_display': Icons.smart_display,
    'subscriptions': Icons.subscriptions,
    'ondemand_video': Icons.ondemand_video,
    'streaming': Icons.ondemand_video,
    'casino': Icons.casino,
    'sports': Icons.sports,
    'sports_soccer': Icons.sports_soccer,
    'soccer': Icons.sports_soccer,
    'sports_basketball': Icons.sports_basketball,
    'basketball': Icons.sports_basketball,
    'sports_baseball': Icons.sports_baseball,
    'sports_football': Icons.sports_football,
    'sports_tennis': Icons.sports_tennis,
    'sports_golf': Icons.sports_golf,
    'golf_course': Icons.golf_course,
    'pool': Icons.pool,
    'fitness_center': Icons.fitness_center,
    'gym': Icons.fitness_center,
    'self_improvement': Icons.self_improvement,
    'spa': Icons.spa,
    'park': Icons.park,
    'attractions': Icons.attractions,
    'beach_access': Icons.beach_access,
    'beach': Icons.beach_access,
    'sailing': Icons.sailing,
    'hiking': Icons.hiking,
    'downhill_skiing': Icons.downhill_skiing,
    'snowboarding': Icons.snowboarding,
    'kayaking': Icons.kayaking,
    'surfing': Icons.surfing,
    'scuba_diving': Icons.scuba_diving,

    // === HEALTH & MEDICAL ===
    'medical_services': Icons.medical_services,
    'health': Icons.medical_services,
    'medical': Icons.medical_services,
    'local_hospital': Icons.local_hospital,
    'hospital': Icons.local_hospital,
    'local_pharmacy': Icons.local_pharmacy,
    'pharmacy': Icons.local_pharmacy,
    'medication': Icons.medication,
    'medicine': Icons.medication,
    'vaccines': Icons.vaccines,
    'health_and_safety': Icons.health_and_safety,
    'healing': Icons.healing,
    'emergency': Icons.emergency,
    'monitor_heart': Icons.monitor_heart,
    'favorite': Icons.favorite,
    'heart': Icons.favorite,
    'psychology': Icons.psychology,
    'face': Icons.face,
    'face_retouching_natural': Icons.face_retouching_natural,
    'spa_outlined': Icons.spa_outlined,
    'child_friendly': Icons.child_friendly,
    'baby': Icons.child_friendly,
    'pregnant_woman': Icons.pregnant_woman,
    'elderly': Icons.elderly,
    'accessible': Icons.accessible,
    'visibility': Icons.visibility,
    'glasses': Icons.visibility,
    'hearing': Icons.hearing,

    // === EDUCATION ===
    'school': Icons.school,
    'education': Icons.school,
    'menu_book': Icons.menu_book,
    'book': Icons.menu_book,
    'auto_stories': Icons.auto_stories,
    'library_books': Icons.library_books,
    'class': Icons.class_,
    'science': Icons.science,
    'calculate': Icons.calculate,
    'functions': Icons.functions,
    'language': Icons.language,
    'translate': Icons.translate,
    'history_edu': Icons.history_edu,
    'architecture': Icons.architecture,
    'engineering': Icons.engineering,
    'biotech': Icons.biotech,
    'brush': Icons.brush,
    'art': Icons.brush,
    'palette': Icons.palette,
    'draw': Icons.draw,
    'edit': Icons.edit,
    'create': Icons.create,
    'design_services': Icons.design_services,
    'quiz': Icons.quiz,
    'extension': Icons.extension,

    // === WORK & BUSINESS ===
    'work': Icons.work,
    'business': Icons.business,
    'business_center': Icons.business_center,
    'corporate_fare': Icons.corporate_fare,
    'domain': Icons.domain,
    'meeting_room': Icons.meeting_room,
    'groups': Icons.groups,
    'people': Icons.people,
    'person': Icons.person,
    'badge': Icons.badge,
    'contact_mail': Icons.contact_mail,
    'contact_phone': Icons.contact_phone,
    'contacts': Icons.contacts,
    'event': Icons.event,
    'calendar_today': Icons.calendar_today,
    'calendar': Icons.calendar_today,
    'schedule': Icons.schedule,
    'time': Icons.schedule,
    'alarm': Icons.alarm,
    'timer': Icons.timer,
    'hourglass_empty': Icons.hourglass_empty,
    'task': Icons.task,
    'task_alt': Icons.task_alt,
    'checklist': Icons.checklist,
    'assignment': Icons.assignment,
    'note': Icons.note,
    'sticky_note_2': Icons.sticky_note_2,
    'description': Icons.description,
    'folder': Icons.folder,
    'folder_open': Icons.folder_open,
    'topic': Icons.topic,
    'inventory': Icons.inventory,
    'inventory_2': Icons.inventory_2,

    // === TRAVEL & VACATION ===
    'luggage': Icons.luggage,
    'travel': Icons.luggage,
    'flight_takeoff': Icons.flight_takeoff,
    'flight_land': Icons.flight_land,
    'connecting_airports': Icons.connecting_airports,
    'local_airport': Icons.local_airport,
    'airport_shuttle': Icons.airport_shuttle,
    'hotel': Icons.hotel,
    'holiday_village': Icons.holiday_village,
    'houseboat': Icons.houseboat,
    'night_shelter': Icons.night_shelter,
    'other_houses': Icons.other_houses,
    'map': Icons.map,
    'explore': Icons.explore,
    'navigation': Icons.navigation,
    'my_location': Icons.my_location,
    'location_on': Icons.location_on,
    'location': Icons.location_on,
    'tour': Icons.tour,
    'flag': Icons.flag,
    'public': Icons.public,
    'language_outlined': Icons.language_outlined,

    // === PETS ===
    'pets': Icons.pets,
    'pet': Icons.pets,
    'cruelty_free': Icons.cruelty_free,

    // === CHARITY & DONATIONS ===
    'volunteer_activism': Icons.volunteer_activism,
    'charity': Icons.volunteer_activism,
    'donate': Icons.volunteer_activism,
    'handshake': Icons.handshake,

    // === INSURANCE ===
    'security': Icons.security,
    'insurance': Icons.security,
    'shield': Icons.shield,
    'verified_user': Icons.verified_user,
    'health_insurance': Icons.health_and_safety,
    'car_crash': Icons.car_crash,
    'home_work': Icons.home_work,
    'umbrella': Icons.umbrella,

    // === TAXES & GOVERNMENT ===
    'gavel': Icons.gavel,
    'taxes': Icons.gavel,
    'balance': Icons.balance,
    'how_to_vote': Icons.how_to_vote,
    'policy': Icons.policy,
    'admin_panel_settings': Icons.admin_panel_settings,

    // === INCOME CATEGORIES ===
    'trending_up': Icons.trending_up,
    'income': Icons.trending_up,
    'salary': Icons.work,
    'monetization_on': Icons.monetization_on,
    'payments_outlined': Icons.payments_outlined,
    'real_estate_agent': Icons.real_estate_agent,
    'sell_outlined': Icons.sell,
    'moving': Icons.moving,
    'show_chart': Icons.show_chart,
    'insights': Icons.insights,
    'leaderboard': Icons.leaderboard,
    'pie_chart': Icons.pie_chart,
    'bar_chart': Icons.bar_chart,
    'analytics': Icons.analytics,
    'query_stats': Icons.query_stats,

    // === TRANSFERS & SYSTEM ===
    'swap_horiz': Icons.swap_horiz,
    'transfer': Icons.swap_horiz,
    'swap_vert': Icons.swap_vert,
    'sync_alt': Icons.sync_alt,
    'compare_arrows': Icons.compare_arrows,
    'multiple_stop': Icons.multiple_stop,
    'tune': Icons.tune,
    'settings': Icons.settings,
    'more_horiz': Icons.more_horiz,
    'more_vert': Icons.more_vert,
    'apps': Icons.apps,
    'category': Icons.category,
    'label': Icons.label,
    'bookmark': Icons.bookmark,
    'star': Icons.star,
    'grade': Icons.grade,
    'thumb_up': Icons.thumb_up,
    'thumb_down': Icons.thumb_down,
    'help': Icons.help,
    'info': Icons.info,
    'warning': Icons.warning,
    'error': Icons.error,
    'check_circle': Icons.check_circle,
    'cancel': Icons.cancel,
    'add_circle': Icons.add_circle,
    'remove_circle': Icons.remove_circle,
    'add': Icons.add,
    'remove': Icons.remove,

    // === LOANS & DEBTS ===
    'account_balance_outlined': Icons.account_balance_outlined,
    'loan': Icons.account_balance_outlined,
    'credit': Icons.credit_score,
    'credit_score': Icons.credit_score,
    'money_off': Icons.money_off,
    'attach_money_outlined': Icons.attach_money,
    'currency_bitcoin': Icons.currency_bitcoin,
    'currency_pound': Icons.currency_pound,
    'currency_yen': Icons.currency_yen,
    'currency_rupee': Icons.currency_rupee,
    'euro': Icons.euro,
    'euro_symbol': Icons.euro_symbol,
  };

  /// Get IconData from icon name string.
  /// Returns [Icons.category] as default if icon name not found.
  static IconData getIcon(String? name) {
    if (name == null || name.isEmpty) {
      return Icons.category;
    }
    return _icons[name.toLowerCase()] ?? Icons.category;
  }

  /// Check if an icon name exists in the registry.
  static bool hasIcon(String name) {
    return _icons.containsKey(name.toLowerCase());
  }

  /// Get all available icon names.
  static List<String> get availableIcons => _icons.keys.toList()..sort();

  /// Get icons filtered by search query.
  static Map<String, IconData> searchIcons(String query) {
    if (query.isEmpty) return _icons;
    final lowerQuery = query.toLowerCase();
    return Map.fromEntries(
      _icons.entries.where((e) => e.key.contains(lowerQuery)),
    );
  }

  /// Get commonly used icons for quick selection.
  static List<String> get commonIcons => [
    'restaurant',
    'directions_car',
    'shopping_bag',
    'home',
    'receipt',
    'medical_services',
    'school',
    'movie',
    'work',
    'phone',
    'wifi',
    'flight',
    'hotel',
    'pets',
    'volunteer_activism',
    'fitness_center',
    'spa',
    'local_cafe',
    'local_gas_station',
    'credit_card',
    'savings',
    'trending_up',
    'swap_horiz',
    'category',
  ];

  /// Get icon names grouped by category for picker UI.
  static Map<String, List<String>> get iconsByCategory => {
    'Food & Drinks': [
      'restaurant',
      'fastfood',
      'local_cafe',
      'coffee',
      'local_bar',
      'local_pizza',
      'lunch_dining',
      'dinner_dining',
      'breakfast_dining',
      'bakery_dining',
      'icecream',
      'cake',
      'ramen_dining',
      'takeout_dining',
    ],
    'Transportation': [
      'directions_car',
      'local_gas_station',
      'directions_bus',
      'train',
      'subway',
      'flight',
      'two_wheeler',
      'pedal_bike',
      'local_taxi',
      'local_parking',
      'ev_station',
      'car_repair',
    ],
    'Shopping': [
      'shopping_bag',
      'shopping_cart',
      'local_mall',
      'store',
      'checkroom',
      'watch',
      'diamond',
      'redeem',
      'card_giftcard',
      'local_offer',
    ],
    'Home & Utilities': [
      'home',
      'apartment',
      'bed',
      'chair',
      'kitchen',
      'lightbulb',
      'water_drop',
      'local_fire_department',
      'ac_unit',
      'cleaning_services',
      'handyman',
    ],
    'Bills & Payments': [
      'receipt',
      'receipt_long',
      'payments',
      'credit_card',
      'account_balance',
      'wallet',
      'attach_money',
      'savings',
      'local_atm',
    ],
    'Health & Medical': [
      'medical_services',
      'local_hospital',
      'local_pharmacy',
      'medication',
      'vaccines',
      'healing',
      'monitor_heart',
      'favorite',
      'psychology',
    ],
    'Entertainment': [
      'movie',
      'theaters',
      'tv',
      'videogame_asset',
      'sports_esports',
      'music_note',
      'headphones',
      'sports_soccer',
      'fitness_center',
      'spa',
      'park',
      'beach_access',
    ],
    'Education': [
      'school',
      'menu_book',
      'auto_stories',
      'science',
      'calculate',
      'language',
      'brush',
      'palette',
      'design_services',
    ],
    'Work & Business': [
      'work',
      'business',
      'business_center',
      'meeting_room',
      'groups',
      'badge',
      'event',
      'calendar_today',
      'task_alt',
      'assignment',
      'folder',
    ],
    'Travel': [
      'luggage',
      'flight_takeoff',
      'hotel',
      'holiday_village',
      'map',
      'explore',
      'location_on',
      'tour',
    ],
    'Income': [
      'trending_up',
      'monetization_on',
      'real_estate_agent',
      'show_chart',
      'insights',
      'analytics',
    ],
    'System': [
      'swap_horiz',
      'tune',
      'settings',
      'category',
      'label',
      'star',
      'add',
    ],
  };
}
