import 'package:drift/drift.dart';
import 'package:the_accountant/data/models/category.dart';
import 'package:the_accountant/data/models/wallet.dart';
import 'package:the_accountant/data/models/payment_method.dart';
import 'package:the_accountant/data/models/recurring_config.dart';

/// How a transaction row came to exist: entered directly, one leg of a
/// wallet-to-wallet transfer, or generated by a recurrence schedule.
///
/// This is the single canonical definition, and it owns BOTH representations:
///
/// * [storageValue] — what goes in the `transaction_type` text column.
/// * [wireValue] — the integer the sync API exchanges, matching the backend's
///   `TransactionType` enum ordinal.
///
/// Those two used to be maintained as scattered string literals with ad-hoc
/// case conversion, and they had silently drifted apart: a generated occurrence
/// was stored as `recurring_instance`, serialized by a lookup that only matched
/// `recurringinstance` (so it went over the wire as *Regular*), and parsed back
/// as `recurringInstance` — a third spelling that matched neither the column nor
/// the domain policy. A synced recurring instance therefore stopped being
/// recognised as one. Keeping both mappings on the enum makes that class of
/// mismatch impossible.
enum TransactionType {
  regular('regular', 0),
  transfer('transfer', 1),
  recurringInstance('recurring_instance', 2);

  const TransactionType(this.storageValue, this.wireValue);

  /// Value persisted in the Drift `transaction_type` column.
  final String storageValue;

  /// Integer exchanged with the backend `TransactionType` enum.
  final int wireValue;

  /// Parse a stored column value.
  ///
  /// Tolerates the historical spellings (`recurringInstance`, `recurringinstance`)
  /// so a row written by an older build is still classified correctly even before
  /// the schema-13 normalisation has run.
  static TransactionType fromStorage(String? value) {
    if (value == null) return TransactionType.regular;
    final normalized = value.replaceAll('_', '').toLowerCase();
    for (final type in TransactionType.values) {
      if (type.storageValue.replaceAll('_', '').toLowerCase() == normalized) {
        return type;
      }
    }
    return TransactionType.regular;
  }

  /// Parse a value received from the sync API, which may be the integer ordinal
  /// or (from an older server) a string.
  static TransactionType fromWire(dynamic value) {
    if (value is int) {
      for (final type in TransactionType.values) {
        if (type.wireValue == value) return type;
      }
      return TransactionType.regular;
    }
    if (value is num) return fromWire(value.toInt());
    return fromStorage(value?.toString());
  }
}

/// Transaction special types enum (like Cashew)
/// Used for filtering and special handling of transactions
enum TransactionSpecialType {
  /// Default transaction - no special handling
  none,

  /// Future unpaid transaction - shows in "Upcoming" section
  upcoming,

  /// Subscription payment - recurring service payment
  subscription,

  /// Repetitive transaction - recurring non-subscription payment
  repetitive,

  /// Credit - money lent to someone (they owe you)
  credit,

  /// Debt - money borrowed from someone (you owe them)
  debt,
}

/// Transactions table for financial records
@TableIndex(
  name: 'idx_transactions_occurrence_key',
  columns: {#occurrenceKey},
  unique: true,
)
@TableIndex(name: 'idx_transactions_paired', columns: {#pairedTransactionId})
class Transactions extends Table {
  // Primary key - UUID string
  TextColumn get id => text().customConstraint('UNIQUE NOT NULL')();

  // Transaction details (integer minor units / cents)
  IntColumn get amount => integer()();
  TextColumn get title => text().withDefault(const Constant(''))();
  TextColumn get notes => text().nullable()();
  DateTimeColumn get date => dateTime()();

  // Transaction type - income or expense (PRIMARY FIELD)
  // Use this field to determine if transaction is income or expense
  BoolColumn get isIncome => boolean().withDefault(const Constant(false))();

  // @deprecated - Use isIncome instead. Kept for backward compatibility.
  // Will be removed in future version. Do not use in new code.
  TextColumn get type => text().withDefault(const Constant('regular'))();

  // Transaction processing type (regular, transfer, recurring_instance)
  TextColumn get transactionType =>
      text().withDefault(const Constant('regular'))();

  // Foreign keys
  TextColumn get categoryId => text().nullable().references(Categories, #id)();
  TextColumn get walletId => text().references(Wallets, #id)();
  TextColumn get paymentMethodId =>
      text().nullable().references(PaymentMethods, #id)();

  // @deprecated - Use paymentMethodId instead. Kept for backward compatibility.
  TextColumn get paymentMethod => text().nullable()();

  // For transfers - paired transaction
  TextColumn get pairedTransactionId => text().nullable()();

  /// The transfer this row is the fee for, or null.
  ///
  /// A transfer with a charge is three rows: the two equal legs, plus this
  /// expense on whichever wallet the charge came out of. Keeping the fee
  /// separate is what lets the pair stay equal — the invariant both the app and
  /// the backend enforce — while still recording money that genuinely left,
  /// which a transfer on its own never does.
  ///
  /// Deliberately **not** a foreign key. `pairedTransactionId` is one, and being
  /// a non-deferrable self-reference is exactly what forced transfers to be
  /// written in two phases. A soft link keeps insert order irrelevant; the
  /// cascade on delete lives in `TransferService`, which is where the rule
  /// belongs anyway.
  TextColumn get feeForTransactionId => text().nullable()();

  // For recurring instances
  TextColumn get recurringConfigId =>
      text().nullable().references(RecurringConfigs, #id)();

  /// Deterministic idempotency key for a generated recurrence occurrence:
  /// `<recurringConfigId>@<scheduledOccurrenceUtcIso>`.
  ///
  /// Two offline devices that both process the same due date derive the SAME
  /// key, so the unique index below collapses them into one row locally and the
  /// backend's matching unique constraint rejects the duplicate on push.
  /// Null for every non-generated transaction (SQLite treats NULLs as distinct
  /// in a unique index, so ordinary rows are unaffected).
  TextColumn get occurrenceKey => text().nullable()();

  // Budget assignment (for tracking against budgets)
  TextColumn get budgetId => text().nullable()();

  // Objective assignment (for goals/loans)
  TextColumn get objectiveId => text().nullable()();

  // @deprecated - Use RecurringConfigs table instead. Kept for backward compatibility.
  BoolColumn get isRecurring => boolean().withDefault(const Constant(false))();
  // @deprecated - Use RecurringConfigs table instead. Kept for backward compatibility.
  TextColumn get recurrencePattern => text().nullable()();

  // Receipt image
  TextColumn get receiptImageUrl => text().nullable()();

  // Special transaction type (like Cashew)
  IntColumn get specialType => intEnum<TransactionSpecialType>()
      .withDefault(const Constant(0))
      .nullable()();

  // Paid status - for upcoming/debt/credit transactions
  // When true: transaction is paid/settled
  // When false: transaction is still pending
  BoolColumn get isPaid => boolean().withDefault(const Constant(true))();

  // Original due date - stores when transaction was originally due
  // Useful when a transaction is marked as paid (date updates to payment date)
  DateTimeColumn get originalDueDate => dateTime().nullable()();

  // Track partial payments for credit/debt transactions (integer minor units / cents)
  IntColumn get paidAmount => integer().withDefault(const Constant(0))();

  // Skip this payment (for recurring unpaid transactions)
  BoolColumn get skipPaid => boolean().withDefault(const Constant(false))();

  // Sync fields
  TextColumn get serverId => text().nullable()();
  IntColumn get syncStatus => integer().withDefault(
    const Constant(0),
  )(); // 0=synced, 1=create, 2=update, 3=delete

  // Timestamps
  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();
  DateTimeColumn get updatedAt => dateTime().withDefault(currentDateAndTime)();
  DateTimeColumn get deletedAt => dateTime().nullable()();

  @override
  Set<Column> get primaryKey => {id};
}
